# Cops documentation: https://rubocop.readthedocs.io/en/stable/
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-0.71.0_yast_style.yml

Layout/LineLength:
  Max: 120

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/UriEscapeUnescape:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/ModuleLength:
  Max: 500
